version: 0.2
phases:
  install:
    runtime-versions:
        java: openjdk11
        python: 3.7
    commands:
      - |
        python3 -m venv .venv
        . .venv/bin/activate
        pip install --upgrade pip>=20.3
        pip install --upgrade pre-commit cloudformation-cli-java-plugin
  build:
    commands:
      - |
        . .venv/bin/activate
        pre-commit run --all-files
      - |
        . .venv/bin/activate
        if [ "$(ls -A $CODEBUILD_SRC_DIR)" ]; then
          cd $CODEBUILD_SRC_DIR
          dirs=$(find . -name 'aws-transfer-*' -mindepth 1 -maxdepth 1 -type d | sort)
          echo "Folders to build: $dirs"
          for directory in $dirs; do
            cd "$directory"
            mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify --no-transfer-progress
            if [ "$?" -ne 0 ] ; then
                echo "Build failed!"
                exit 1
            fi
            cd ".."
          done
        else
          echo "$CODEBUILD_SRC_DIR is empty"
        fi
    finally:
      - |
        cd $CODEBUILD_SRC_DIR
        dirs=$(find . -name 'aws-transfer-*' -mindepth 1 -maxdepth 1 -type d | sort)
        for directory in $dirs; do
          if [ -f "$directory/rpdk.log" ] ; then
            echo "Logs from $directory"
            cat "$directory/rpdk.log"
          else
            echo "No logs found for $directory"
          fi
        done
