Resources:
  ProfileCustomCertificate:
    Type: AWS::Transfer::Certificate
    Properties:
     Usage: SIGNING
     Certificate: "-----BEGIN CERTIFICATE-----\n MIIDezCCAmOgAwIBAgIESnHn9TANBgkqhkiG9w0BAQUFADBuMQswCQYDVQQGEwJV\n UzERMA8GA1UECBMITmV3IFlvcmsxETAPBgNVBAcTCE5ldyBZb3JrMREwDwYDVQQK\n EwhPcGVuQVMyQjELMAkGA1UECxMCUUExGTAXBgNVBAMTEE9wZW5BUzJCIFRlc3Rp\n bmcwHhcNMTUwNzI3MTgwODQzWhcNMjUwNzI0MTgwODQzWjBuMQswCQYDVQQGEwJV\n UzERMA8GA1UECBMITmV3IFlvcmsxETAPBgNVBAcTCE5ldyBZb3JrMREwDwYDVQQK\n EwhPcGVuQVMyQjELMAkGA1UECxMCUUExGTAXBgNVBAMTEE9wZW5BUzJCIFRlc3Rp\n bmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC+1kS4nbcX8Sjp4znp\n AHRMmLy0o4Z5WTflL2NmXdLiO6wtIzrTOfmyHgZt/itvV5CkWHC7XkPT99LdnWuT\n slVYfMhrphcHSV2se5F0Cp7pguv8D3ooNz/XjO0vsq6Xtst2pU/3CCmuCt78H5BP\n YfzcUiBgHJ1rm5BVflPt90fIfkFNatsWwTU+2YuoUDW3FlUbQ/8Ym7NO24IDfAIs\n URETzGPEzYjYsy3K/5Jl1SWbYkyJCD6fHY8qjy2s6dOxmn2ncDqYx4ziPJUkQUdc\n TvLwVQEJN3uMFYnHetgfmB9Ny7W+w7a/bmrGmZA7DyWKyL6m77fsjc7xgTSDRoL3\n UJaVAgMBAAGjITAfMB0GA1UdDgQWBBQ+ASEQrWoVxlNKBz0Bj8PXc4GaaDANBgkq\n hkiG9w0BAQUFAAOCAQEAL6zajyvmW07/8V2WaGsr95cMw/yQvqqhiOD+RDaNV0Pw\n N2BQmVtuOYKyiC3yTW/FFed0SfbqwU8Q84/8O9S47HJZwqUI+pi/OMHf2+Q4hsMq\n 7+3Jf7qiM26zwVzB2vd0Iz4JbfWQNRHyaiygNN8lJ++xHQ27H3sxxsQzs/fEPvA7\n yj8dI3eCVOFHipupHD7BBJ/tscY553mIyHNoVbGAk2DE4WDZ1DnvnC2oJK7giafF\n IFwbhQLGEE36OYyHoPhKGXOZWfGoBo2jlOGFdKhJBO91xPV8YHWwP0UMcvi8K7Uq\n u6rBwXqolY+nuoLgm5FYzYskgUdksxvDkAHE1cE9tQ==\n -----END CERTIFICATE-----\n"
     ActiveDate: 2022-03-22T18:04:35Z
     InactiveDate: 2022-08-04T18:04:35Z
Outputs:
  ProfileCustomCertificate:
    Value:
      Ref: ProfileCustomCertificate
    Export:
      Name: awstransferprofilecto1
