AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
              StringLike:
                aws:SourceArn:
                  Fn::Sub: arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/resource/AWS-Transfer-WebApp/*
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "iam:PassRole"
                - "sso:CreateApplication"
                - "sso:DeleteApplication"
                - "sso:DescribeApplication"
                - "sso:GetApplicationAccessScope"
                - "sso:GetApplicationAuthenticationMethod"
                - "sso:GetApplicationGrant"
                - "sso:ListApplicationAccessScopes"
                - "sso:ListApplicationAuthenticationMethods"
                - "sso:ListApplicationGrants"
                - "sso:ListApplications"
                - "sso:PutApplicationAccessScope"
                - "sso:PutApplicationAuthenticationMethod"
                - "sso:PutApplicationGrant"
                - "sso:UpdateApplication"
                - "transfer:CreateWebApp"
                - "transfer:DeleteWebApp"
                - "transfer:DeleteWebAppCustomization"
                - "transfer:DescribeWebApp"
                - "transfer:DescribeWebAppCustomization"
                - "transfer:ListWebApps"
                - "transfer:TagResource"
                - "transfer:UnTagResource"
                - "transfer:UpdateWebApp"
                - "transfer:UpdateWebAppCustomization"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
